"""Protocol-style desktop adapter interfaces."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Protocol


class AppsAdapter(Protocol):
    def launch(self, app: str) -> str: ...

    def focus(self, app: str) -> str: ...

    def quit(self, app: str) -> str: ...


class WindowsAdapter(Protocol):
    def list_windows(self) -> list[str]: ...

    def switch(self, window: str) -> str: ...

    def minimize(self, window: str) -> str: ...

    def maximize(self, window: str) -> str: ...

    def set_fullscreen(self, window: str, enabled: bool) -> str: ...

    def set_keep_above(self, window: str, enabled: bool) -> str: ...

    def set_shaded(self, window: str, enabled: bool) -> str: ...

    def set_keep_below(self, window: str, enabled: bool) -> str: ...

    def set_on_all_desktops(self, window: str, enabled: bool) -> str: ...

    def restore(self, window: str) -> str: ...

    def close(self, window: str) -> str: ...


class TimeAdapter(Protocol):
    def now(self) -> str: ...


class PowerAdapter(Protocol):
    def battery_status(self) -> str: ...


class AudioAdapter(Protocol):
    def get_volume(self) -> int: ...

    def set_volume(self, percent: int) -> str: ...

    def set_muted(self, muted: bool) -> str: ...

    def is_muted(self) -> bool: ...


class ClipboardAdapter(Protocol):
    def get_text(self) -> str: ...

    def set_text(self, text: str) -> str: ...

    def clear(self) -> str: ...


class TextInputAdapter(Protocol):
    def copy_selection(self) -> str: ...

    def paste(self) -> str: ...

    def type_text(self, text: str) -> str: ...

    def press_key(self, key: str) -> str: ...


class NetworkAdapter(Protocol):
    def set_wifi_enabled(self, enabled: bool) -> str: ...

    def wifi_status(self) -> str: ...

    def is_wifi_enabled(self) -> bool: ...

    def disconnect_current(self) -> str: ...

    def connect_known_ssid(self, ssid: str) -> str: ...


class NotificationsAdapter(Protocol):
    def show(self, title: str, message: str) -> str: ...


class FilesAdapter(Protocol):
    desktop_dir: Path

    def list_recent(self, root: Path | None = None) -> list[Path]: ...

    def open_path(self, path: Path) -> str: ...

    def create_folder(self, root: Path, name: str) -> Path: ...

    def remove_folder(self, path: Path) -> None: ...

    def remove_file(self, path: Path) -> None: ...

    def rename_path(self, path: Path, new_name: str) -> Path: ...

    def move_path(self, path: Path, destination_dir: Path) -> Path: ...


@dataclass(slots=True)
class AdapterSet:
    apps: AppsAdapter | None = None
    windows: WindowsAdapter | None = None
    time: TimeAdapter | None = None
    power: PowerAdapter | None = None
    audio: AudioAdapter | None = None
    clipboard: ClipboardAdapter | None = None
    text_input: TextInputAdapter | None = None
    network: NetworkAdapter | None = None
    notifications: NotificationsAdapter | None = None
    files: FilesAdapter | None = None
